POC for simpler error management
 + Defines callable object with less macro and more proper types.
 + Raise the point where requirements error are triggered to shorten
   compile-time error message.
 + Raise the point where assert are fired to locate them inside the
   actual function code.
 + Use different object to prevent conditionnal or decorated verison of
   functions to participate in regular cases overload resolution.

Sample error message:

Code:
```c++

int main()
{
  eve::wide<float> x{};
  eve::wide<int>   y{};

  return eve::add(x,y);
}
```

Error on g++

```
main.cpp: In function ‘int main()’:
main.cpp:9:18: error: no match for call to ‘(const eve::detail::callable_add_) (eve::sse_abi_v0::wide<float>&, eve::sse_abi_v0::wide<int>&)’
    9 |   return eve::add(x,y);
      |          ~~~~~~~~^~~~~
In file included from main.cpp:2:
/home/falcou/dev/project/eve/include/eve/function/add.hpp:101:38: note: candidate: ‘template<class T0, class ... Tn>  requires (value<T0>) && ((... && value<Tn>)) && ((compatible_values<T0, Tn> && ...)) constexpr auto eve::detail::callable_add_::operator()(T0, Tn ...) const’
  101 |       EVE_FORCEINLINE constexpr auto operator()(T0 a0, Tn... an) const noexcept
      |                                      ^~~~~~~~
/home/falcou/dev/project/eve/include/eve/function/add.hpp:101:38: note:   template argument deduction/substitution failed:
/home/falcou/dev/project/eve/include/eve/function/add.hpp:101:38: note: constraints not satisfied
/home/falcou/dev/project/eve/include/eve/function/add.hpp: In substitution of ‘template<class T0, class ... Tn>  requires (value<T0>) && ((... && value<Tn>)) && ((compatible_values<T0, Tn> && ...)) constexpr auto eve::detail::callable_add_::operator()(T0, Tn ...) const [with T0 = eve::sse_abi_v0::wide<float>; Tn = {eve::sse_abi_v0::wide<int, eve::fixed<4> >}]’:
main.cpp:9:18:   required from here
/home/falcou/dev/project/eve/include/eve/function/add.hpp:101:38:   required by the constraints of ‘template<class T0, class ... Tn>  requires (value<T0>) && ((... && value<Tn>)) && ((compatible_values<T0, Tn> && ...)) constexpr auto eve::detail::callable_add_::operator()(T0, Tn ...) const’
/home/falcou/dev/project/eve/include/eve/function/add.hpp:101:38: note: the expression ‘(compatible_values<T0, Tn> && ...) [with T0 = eve::sse_abi_v0::wide<float, eve::fixed<4> >; Tn = {eve::sse_abi_v0::wide<int, eve::fixed<4> >}]’ evaluated to ‘false’
```

instead of:

```
<source>: In function 'int main()':
<source>:9:18: error: no match for call to '(const eve::detail::callable_object<eve::tag::add_>) (eve::sse_abi_v0::wide<float>&, eve::sse_abi_v0::wide<int>&)'
    9 |   return eve::add(x,y);
      |          ~~~~~~~~^~~~~
In file included from /opt/compiler-explorer/libs/eve/trunk/include/eve/detail/implementation.hpp:10,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/constant/allbits.hpp:10,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/detail/function/simd/common/friends.hpp:12,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/detail/function/friends.hpp:11,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/arch/cpu/base.hpp:11,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/arch/cpu/wide.hpp:11,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/arch/wide.hpp:10,
                 from /opt/compiler-explorer/libs/eve/trunk/include/eve/wide.hpp:18,
                 from <source>:1:
/opt/compiler-explorer/libs/eve/trunk/include/eve/function/add.hpp:89:3: note: candidate: 'template<class ... Args>  requires (tag_dispatchable<eve::tag::add_, Args ...>) || (supports_add_<Args ...>) constexpr auto eve::detail::callable_object<eve::tag::add_, Dummy>::operator()(Args&& ...) const [with Args = {Args ...}; Dummy = void]'
   89 |   EVE_MAKE_CALLABLE(add_, add);
      |   ^~~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/eve/trunk/include/eve/function/add.hpp:89:3: note:   template argument deduction/substitution failed:
/opt/compiler-explorer/libs/eve/trunk/include/eve/function/add.hpp:89:3: note: constraints not satisfied
<source>: In substitution of 'template<class ... Args>  requires (tag_dispatchable<eve::tag::add_, Args ...>) || (supports_add_<Args ...>) constexpr auto eve::detail::callable_object<eve::tag::add_>::operator()<Args ...>(Args&& ...) const [with Args = void]':
<source>:9:18:   required from here
/opt/compiler-explorer/libs/eve/trunk/include/eve/function/add.hpp:89:3:   required by the constraints of 'template<class Dummy> template<class ... Args>  requires (tag_dispatchable<eve::tag::add_, Args ...>) || (supports_add_<Args ...>) constexpr auto eve::detail::callable_object<eve::tag::add_, Dummy>::operator()(Args&& ...) const'
/opt/compiler-explorer/libs/eve/trunk/include/eve/function/add.hpp:89:3: note: no operand of the disjunction is satisfied
   89 |   EVE_MAKE_CALLABLE(add_, add);
      |   ^~~~~~~~~~~~~~~~
cc1plus: note: set '-fconcepts-diagnostics-depth=' to at least 2 for more detail
```

Notice that the error is now on the callable and not inside the internal concept checks.
No need to use the '-fconcepts-diagnostics-depth=' options to get 1000 more lines.

The positionning of the actual concept check on the callable (and its deocrated form)
helps make the code stands for itself and don't duplicate the checks all over the
implementation.