maybe fix gcc concept bug
The error

```
/__w/eve/eve/include/eve/concept/scalar.hpp:45:49: error: satisfaction value of atomic constraint '(is_plain<T>)() [with T = typename eve::arm_abi_v0::wide<Type, Size>::value_type]' changed from 'false' to 'true'
   45 | concept plain_scalar_value = detail::is_plain<T>();
      |                              ~~~~~~~~~~~~~~~~~~~^~
/__w/eve/eve/include/eve/arch/cpu/logical_wide.hpp:77:11: note: satisfaction value first evaluated to 'false' from here
   77 |     using bits_type = wide<as_integer_t<Type, unsigned>, Cardinal>;
      |           ^~~~~~~~~
```

I think the problem is that as_integer works for wide and logical while being used in logical